sudo: true
dist: xenial

language: c

addons:
  apt:
    packages:
      - check
      - libasound2-dev
      - libbluetooth-dev
      - libbsd-dev
      - libdbus-1-dev
      - libfdk-aac-dev
      - libglib2.0-dev
      - libmp3lame-dev
      - libmpg123-dev
      - libncurses5-dev
      - libreadline-dev
      - libsbc-dev
      - python3-docutils

before_script:
  - mkdir -p m4
  - autoreconf --install && mkdir build && cd build

script:
  - ../configure --enable-test && make && make check
  - cat test/*.log
  - ../configure --enable-test --enable-debug && make && make check
  - cat test/*.log
  - ../configure --enable-test --enable-manpages --enable-aac --enable-msbc && make && make check
  - cat test/*.log
  - ../configure --enable-mp3lame --enable-mpg123 --enable-ofono && make
  - ../configure --enable-mp3lame --enable-ofono --enable-upower && make
